package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

// User is a platform-wide fan account — deliberately not tenant-scoped.
// See migrations/000003_users_and_auth.up.sql: the same fan account
// should work across every club on the platform, with the relationship to
// any one tenant expressed via Membership, not by scoping the account
// itself.
type User struct {
	ID              uuid.UUID
	Email           string
	Phone           string
	PasswordHash    string // never populate this on a path that reaches an HTTP response
	FirstName       string
	LastName        string
	Status          UserStatus
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UserRepository interface {
	Create(ctx context.Context, u *User) error
	GetByID(ctx context.Context, id uuid.UUID) (*User, error)
	GetByEmail(ctx context.Context, email string) (*User, error)
	Update(ctx context.Context, u *User) error
}

// RefreshToken is a persisted, individually revocable refresh token. Only
// TokenHash is ever stored — the raw token is generated by the auth
// service, returned to the client exactly once, and never written to the
// database.
type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	UserAgent string
	IPAddress string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type RefreshTokenRepository interface {
	Create(ctx context.Context, rt *RefreshToken) error
	GetByTokenHash(ctx context.Context, tokenHash string) (*RefreshToken, error)
	Revoke(ctx context.Context, id uuid.UUID) error
	// RevokeAllForUser powers "log out everywhere" / a suspected
	// compromised account.
	RevokeAllForUser(ctx context.Context, userID uuid.UUID) error
}
