package domain

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusDeleted   UserStatus = "deleted"
)

// UserRole distinguishes a platform-wide fan account from a tenant-scoped
// club-staff/admin account. See migrations/000013_user_roles.up.sql — a
// real RBAC system (granular permissions, multiple staff roles per club)
// is future work; this is deliberately just enough to gate admin
// endpoints.
type UserRole string

const (
	UserRoleFan   UserRole = "fan"
	UserRoleAdmin UserRole = "admin"
)

// User is a fan account (Role == UserRoleFan, TenantID nil) or a
// tenant-scoped club-staff account (Role == UserRoleAdmin, TenantID set).
// Fans are deliberately platform-wide — see
// migrations/000003_users_and_auth.up.sql: the same fan account should
// work across every club on the platform. Admin accounts belong to
// exactly one club; the database enforces the pairing (see migration
// 000013's CHECK constraint) so this struct can't represent an
// inconsistent admin-with-no-tenant or fan-with-a-tenant.
type User struct {
	ID              uuid.UUID
	Email           string
	Phone           string
	PasswordHash    string // never populate this on a path that reaches an HTTP response
	FirstName       string
	LastName        string
	Status          UserStatus
	Role            UserRole
	TenantID        *uuid.UUID
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UserRepository interface {
	Create(ctx context.Context, u *User) error
	GetByID(ctx context.Context, id uuid.UUID) (*User, error)
	GetByEmail(ctx context.Context, email string) (*User, error)
	Update(ctx context.Context, u *User) error
}

// RefreshToken is a persisted, individually revocable refresh token. Only
// TokenHash is ever stored — the raw token is generated by the auth
// service, returned to the client exactly once, and never written to the
// database.
type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	UserAgent string
	IPAddress string
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
}

type RefreshTokenRepository interface {
	Create(ctx context.Context, rt *RefreshToken) error
	GetByTokenHash(ctx context.Context, tokenHash string) (*RefreshToken, error)
	Revoke(ctx context.Context, id uuid.UUID) error
	// RevokeAllForUser powers "log out everywhere" / a suspected
	// compromised account.
	RevokeAllForUser(ctx context.Context, userID uuid.UUID) error
}
